src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $Price = null;

    /**
     * @var Collection<int, SubCategory>
     */
    #[ORM\ManyToMany(targetEntity: SubCategory::class, inversedBy: 'products')]
    private Collection $SubCategory;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $stock = null;

    /**
     * @var Collection<int, AddProductHistory>
     */
    #[ORM\OneToMany(targetEntity: AddProductHistory::class, mappedBy: 'Product')]
    private Collection $addProductHistories;

    /**
     * @var Collection<int, OrderProducts>
     */
    #[ORM\OneToMany(targetEntity: OrderProducts::class, mappedBy: 'product')]
    private Collection $orderProducts;

    public function __construct()
    {
        $this->SubCategory = new ArrayCollection();
        $this->addProductHistories = new ArrayCollection();
        $this->orderProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection<int, SubCategory>
     */
    public function getSubCategory(): Collection
    {
        return $this->SubCategory;
    }

    public function addSubCategory(SubCategory $subCategory): static
    {
        if (!$this->SubCategory->contains($subCategory)) {
            $this->SubCategory->add($subCategory);
        }

        return $this;
    }

    public function removeSubCategory(SubCategory $subCategory): static
    {
        $this->SubCategory->removeElement($subCategory);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    /**
     * @return Collection<int, AddProductHistory>
     */
    public function getAddProductHistories(): Collection
    {
        return $this->addProductHistories;
    }

    public function addAddProductHistory(AddProductHistory $addProductHistory): static
    {
        if (!$this->addProductHistories->contains($addProductHistory)) {
            $this->addProductHistories->add($addProductHistory);
            $addProductHistory->setProduct($this);
        }

        return $this;
    }

    public function removeAddProductHistory(AddProductHistory $addProductHistory): static
    {
        if ($this->addProductHistories->removeElement($addProductHistory)) {
            // set the owning side to null (unless already changed)
            if ($addProductHistory->getProduct() === $this) {
                $addProductHistory->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderProducts>
     */
    public function getOrderProducts(): Collection
    {
        return $this->orderProducts;
    }

    public function addOrderProduct(OrderProducts $orderProduct): static
    {
        if (!$this->orderProducts->contains($orderProduct)) {
            $this->orderProducts->add($orderProduct);
            $orderProduct->setProduct($this);
        }

        return $this;
    }

    public function removeOrderProduct(OrderProducts $orderProduct): static
    {
        if ($this->orderProducts->removeElement($orderProduct)) {
            // set the owning side to null (unless already changed)
            if ($orderProduct->getProduct() === $this) {
                $orderProduct->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\SubCategory;
use App\Repository\ProductRepository;
use App\Repository\CategoryRepository;
use App\Repository\SubCategoryRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class HomePageController extends AbstractController
{
    #[Route('/', name: 'app_home_page', methods:['GET'])]
    public function index(ProductRepository $productRepo, CategoryRepository $categoryRepository, Request $request, PaginatorInterface $paginator): Response
    {   
        // $search= $productRepo->SearchEngine('mma');
        // dd($search);

        $data = $productRepo->findby([],['id'=>"DESC"]);
        $products = $paginator->paginate(
            $data,
            $request->query->getInt('page',1),
            8
        );


        return $this->render('home_page/index.html.twig', [
            'controller_name' => 'HomePageController',
            'products' => $products,
            'categories'=>$categoryRepository ->findAll()
        ]);
    }

     #[Route('/product/{id}/show', name: 'app_home_product_show', methods:['GET'])]
    public function showProduct(Product $product, ProductRepository $productRepository,CategoryRepository $categorieRepository): Response
    {   
        $lastProductsAdd = $productRepository->findBy([],['id'=>'DESC'],5);

        return $this->render('home_page/show.html.twig', [
            
            'product' => $product,
            'products' =>$lastProductsAdd,
            'categories'=>$categorieRepository->findAll()
        ]);
    }

     #[Route('/product/subcategory/{id}/filter', name: 'app_home_product_filter', methods:['GET'])]
    public function filter($id,SubCategoryRepository $subCategoryRepository, CategoryRepository $categoryRepository): Response

    {   //on recupere la sous categorie correspondante à l'id passé en paramètre
        // on accede aux products de cette sous catégorie
        $product = $subCategoryRepository->find($id)->getProducts();
        //on récupère la sous catégorie complète (objet)
        $subCategory = $subCategoryRepository->find($id);

        return $this->render('home_page/filter.html.twig', [
        'products'=>$product,// liste des produits liés à la sous catégorie
        'subCategory'=>$subCategory,//l'objet sous catégorie qui correspond avec l'id
        'categories'=>$categoryRepository->findAll()//la liste de toutes les catégories vie la repo
            
            
        ]);
    }
}

templates/home_page/filter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sous-catégories{% endblock %}

{% block body %}
<div class="container">
    <h1 class="mb-5 mt-5">{{ subCategory.name }}</h1>
    <div class="row">
        {% for product in products %}
            <div class="col-md-3 mt-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ asset('uploads/images/'~product.image)}}" class="imgproduct card-img-top" alt="image des produits">
                    <div class="card-body">
                        <a class="titleProductLink" href="{{ path('app_home_product_show',{'id':product.id}) }} "><h5 class="card-title titleProduct">{{ product.name }}</h5></a>
                        <p class="card-text">{{ product.description|slice(0,60) }}...</p>
                        <h3>{{ product.price }} €</h3> <!-- altgr + e pour le sigle euro-->
                        <a href="{{ path('app_cart_new',{'id':product.id}) }}" class="btn btn-outline-success">Ajouter au panier</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/home_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello User{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-md-3 g-4 ">
                <div class="card" style="width: 18rem;">
                    <img src="{{asset('uploads/images/'~ product.image)}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a class="titleProductionLink" href="{{path('app_home_product_show',{'id':product.id})}}">
                        <h5 class="card-title"> {{ product.name }} </h5>
                        </a>
                        <p class="card-text text-truncate">{{ product.Description |slice(0,60) }}...</p>
                        <h3>{{product.Price}}€</h3>
                        <a href="{{path('app_cart_new',{'id':product.id})}}" class="btn btn-primary">Ajouter au panier</a>
                    </div>
                </div>
            </div>
   

        {% endfor %}
    </div>
    <br>
    {{knp_pagination_render(products,'layouts/paginator.html.twig')}}
</div>

{% endblock %}

templates/home_page/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello User{% endblock %}

{% block body %}

<div class="container">
    <div class="card mb-12 m-5">
        <div class="row g-0">
            <div class="col-md-4">
            <img class="productImage" src="{{asset('uploads/images/'~ product.image)}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">{{product.Description}}</p>
                <p class="card-text">{{product.Price}}€</p>
                {# <p class="card-text">Only {{product.stock}} available</p> #}
                <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <h2 class="mt-5">Derniers produits ajoutés</h2>
    <div class="row">
        {% for product in products %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{asset('uploads/images/'~ product.image)}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a class="titleProductionLink" href="{{path('app_home_product_show',{'id':product.id})}}">
                    <h5 class="card-title"> {{ product.name }} </h5>
                    </a>
                    <p class="card-text">{{ product.Description |slice(0,60) }}...</p>
                    <h3>{{product.Price}}€</h3>
                    <a href="{{path('app_cart_new',{'id':product.id})}}" class="btn btn-primary">Ajouter au panier</a>
                </div>
            </div>
        </div>
   

            {% endfor %}
    </div>
</div>

{% endblock %}